### ISSUE TITLE
SCIM 1.1 SDK HTTPS Proxy is not woking

### ISSUE THREAD

**Issue by ajit-pawar-sp** [pingidentity/scim#18]
Hi Experts,

We are using SCIM 1.1 SDK version 1.8.18. The SCIM SDK is working fine for HTTP proxy but Not working HTTPS proxy. It gives error Unrecognized SSL message, plaintext connection?
Could you please help on this.
Thanks in advance!!!

**Comment by kennethleo** [comment]
Are you sure the connection is secure?  The error message seems to indicate otherwise.

https://stackoverflow.com/questions/6532273/unrecognized-ssl-message-plaintext-connection-exception

**Comment by ajit-pawar-sp** [comment]
We will check with HTTPS client till then we can close this issue.
