### ISSUE TITLE
SCIM filter cannot parse 'ne' not-equal operator 

### ISSUE THREAD

**Issue by beldahanit** [pingidentity/scim#30]
I suggest to implement "ne" - not-equal operator for parsing SCIM filters as it is in SCIM 2 SDK.

**Comment by kqarryzada** [comment]
@beldahanit, as far as I'm aware, the SCIM 1.1 standard does not support `ne` filters. [draft-scim-api-01 section 3.2.2.1](https://datatracker.ietf.org/doc/html/draft-scim-api-01#section-3.2.2.1) contains an exhaustive list of supported filter operators, which does not include a NOT filter.
